In [1]:
import sympy as sym
import numpy as np
from IPython.display import display,Math

In [4]:
A = np.array([[1,2],[3,4]])

print(A)
display(Math(sym.latex((A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [7]:
B = np.zeros([4,6])

print(B)
display(Math(sym.latex((B))))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


<IPython.core.display.Math object>

In [14]:

from sympy.abc import x,y

C = np.([3,3])
expr = (4+x)*(2-y)

for i in range(0,3):
    for j in range(0,3):
        C[i][j] = sym.latex(expr.subs(x,i).subs(y,j).evalf())

print(C)

AttributeError: module 'numpy' has no attribute 'list'